name: Deploy commit to Firebase Hosting live channel
'on':
  push:
   branches:
    - develop
env:
  BIOPORTAL_APIKEY: ${{ secrets.BIOPORTAL_APIKEY }}
jobs:
  build_and_deploy_to_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_PRO_AUTH_TOKEN }}"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run build

      - name: Deploy to firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: hosting:channel:deploy develop
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRED_CA431 }}'

      - run: npm run test-ci
